### ISSUE TITLE
[Bug]: 마이페이지에서 이미지가 안 올라갑니다 

### ISSUE THREAD

**Issue by easyspubjava** [Kernel360/f1-KernelSquare-backend#242]
### 연락 정보

eunjong.park@gmail.com

### 어떤 버그가 있었나요?

마이페이지에서 사진을 올렸는데 안올라갑니다. 사진을 선택하고 올렸는데 403 에러가 났습니다.
<img width="440" alt="스크린샷 2024-02-08 오전 11 27 48" src="https://github.com/Kernel360/f1-KernelSquare-backend/assets/37524201/355320c6-dc07-45f0-9d1f-0024a652cd16">

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] KernelSquare의 Code of Conduct에 동의합니다.

**Comment by mooncw** [comment]
버그를 제보해주셔서 감사합니다.
해당 버그는 이미지 파일 크기가 커서 발생한 문제로 확인되었습니다.

**Comment by easyspubjava** [comment]
그럼 그렇게 ㅁ세지를 띄워주시면 감사하겠습니다
무응답이라 에러인것 같습니다

2024년 2월 8일 (목) 오후 2:00, mooncw ***@***.***>님이 작성:
