### ISSUE TITLE
[Bug]: placeholder 변경 요청

### ISSUE THREAD

**Issue by cgk95** [Kernel360/f1-KernelSquare-backend#243]
### 어떤 버그가 있었나요?

마이페이지의 readme.md 를 수정하려고 할 때, placeholder 가 "질문을 작성해주세요" 입니다. 질문 작성을 하는 부분은 아닌 거 같아서 변경 요청합니다

<img width="1314" alt="image" src="https://github.com/Kernel360/f1-KernelSquare-backend/assets/73059667/95df4b40-754c-4951-ad15-5fce2ab67588">

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Naver Whale

### Code of Conduct

- [X] KernelSquare의 Code of Conduct에 동의합니다.

**Comment by mooncw** [comment]
버그 제보 감사합니다.
반영하도록 하겠습니다.

**Comment by JeongwooHam** [comment]
수정 완료하였습니다!:)
