### ISSUE TITLE
[Bug]: 프로필 이미지 변경 기능이 오동작합니다

### ISSUE THREAD

**Issue by cgk95** [Kernel360/f1-KernelSquare-backend#244]
### 어떤 버그가 있었나요?

1. 로그인한 이후, 프로필 이미지 변경을 시도합니다. (.png 이미지를 업로드하였습니다.)
![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/73059667/76bb66b6-cb10-4ced-8622-6e91175da0cb)

2. 변경 실패 에러가 발생합니다.
![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/73059667/66172e2b-3b94-4414-b63e-19620f1a302a)

3. 개발자 도구를 보면 해당 기능은 로그인이 필요하다는 응답입니다.
![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/73059667/a531d257-bf59-400f-aec8-c56ed3f4d024)
![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/73059667/98c3991b-d30d-4cab-85d9-1fc01858ab57)
![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/73059667/eefe8726-1627-4b9f-9a6a-0c2c3511eaab)

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Naver Whale

### Code of Conduct

- [X] KernelSquare의 Code of Conduct에 동의합니다.

**Comment by mooncw** [comment]
버그 제보 감사합니다.
해당 버그는 인지하고 있었고 추후 수정할 예정입니다.
