### ISSUE TITLE
[chore]  @AuthenticationPrincipal 사용

### ISSUE THREAD

**Issue by Hju95** [Kernel360/f1-KernelSquare-backend#301]
### 관련 도메인
 @AuthenticationPrincipal MemberAdapter memberAdapter 하는 전 도메인
### 상세내용
-   @AuthenticationPrincipal MemberAdapter memberAdapter 을 언제 쓰고 언제 안써도 되는지에 대한 라인 고민
- 모각코 기준 생성 시에만 쓰고 있는데 모든 멤버가 이를 인지한 채 PR 머지 진행
- 다른 분들의 의견 들어보고 싶습니다.
- 제 생각은 수정,삭제 시에도 필요하다고 생각되어서 이후 다른 도메인도 빠져있다면 추가하면 좋을 것 같네요

**Comment by mooncw** [comment]
api 요청을 한 멤버가 존재한다면 모두 `@AuthenticationPrincipal` 써야한다고 생각합니다.

**Comment by RossKWSang** [comment]
저도 수정 삭제에 체크 로직이 추가되어야한다고 생각되며, 응답코드도 송출해야한다고 생각합니다.

**Comment by Hju95** [comment]
추가됨
