### ISSUE TITLE
[chore] 서비스 안내페이지 만들기 

### ISSUE THREAD

**Issue by RossKWSang** [Kernel360/f1-KernelSquare-backend#311]
### 관련 도메인
All

### 개요
개발자 Q&A, 커피챗, 모각코 기능에 대한 사용 안내
처음 온 사용자가 한눈에 볼 수 있도록 내용을 설계

### 상세내용
- 작성된 내용을 프론트와 디자이너에게 전달

**Comment by fingersdanny** [comment]
서비스 랜딩페이지 추가로 해결
