### ISSUE TITLE
[bug] 답변 랭킹을 매길 때 커널스퀘어 AI 인턴이 작성한 답변도 랭킹에 들 수도 있는 문제

### ISSUE THREAD

**Issue by mooncw** [Kernel360/f1-KernelSquare-backend#325]
### 관련 도메인
스케줄러

### 개요
우리의 막내 '커널스퀘어 AI 인턴'이 단 답변은 답변 랭킹 시스템에서 제외하기 위함

### 상세내용
- rankAnswer 스케줄러에서 답변 작성자의 닉네임에 조건문을 달 예정

**Comment by fingersdanny** [comment]
Whooray
