### ISSUE TITLE
공지 CRUD 완성하기

### ISSUE THREAD

**Issue by mooncw** [Kernel360/f1-KernelSquare-backend#337]
@fingersdanny 
api 관련 로직 필요한 수정 해주시고,
플라이웨이 notice 테이블 생성 추가 해주세요.

**Comment by fingersdanny** [comment]
> @fingersdanny api 관련 로직 필요한 수정 해주시고, 플라이웨이 notice 테이블 생성 추가 해주세요.

힘들어요./..
