### ISSUE TITLE
[Bug]: 프로필 사진 변경하려는데 500애러 발생합니다 !

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/f1-KernelSquare-backend#340]
### 어떤 버그가 있었나요?

1. 프로필 사진을 교체하려는데 아무일도 발생하지 않습니다.
개발자도구를 켜서 다시 확인해보니 500에러가 발생합니다.

![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/59242594/4d37f9be-5846-4020-bb0b-07f6e2367913)

### Version

1.0.0 (Default)

### Code of Conduct

- [X] KernelSquare의 Code of Conduct에 동의합니다.

**Comment by fingersdanny** [comment]
이미지 URL이 너무 길어져서 생기는 이슈 현재 대응 중에 있습니다.
