### ISSUE TITLE
[Bug]: 커피챗 삭제 정책으로 인해 삭제 실패시 유저가 인식할 수 없습니다

### ISSUE THREAD

**Issue by aqrms** [Kernel360/f1-KernelSquare-backend#341]
### 어떤 버그가 있었나요?

![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/111513287/2076f03b-5c8b-49b6-9b6b-8ee997949c99)
커피챗 삭제관련 정책이 있는것 같은데 에러 메세지를 화면에서 볼 수 없어서 유저가 인지할 수 없습니다

### Version

1.0.0 (Default)

### 어느 브라우저에서 사용 중 일어난 일인가요?

Chrome

### Code of Conduct

- [X] KernelSquare의 Code of Conduct에 동의합니다.

**Comment by fingersdanny** [comment]
네 확인하겠습니다.
