### ISSUE TITLE
[Bug]: 로그인 전에 투표를 하면 "자신의 답변에는 투표할 수 없습니다" 메시지가 나옵니다.

### ISSUE THREAD

**Issue by corazzon** [Kernel360/f1-KernelSquare-backend#356]
### 연락 정보

joeunpark@gmail.com

### 어떤 버그가 있었나요?

로그인 전에 투표를 하면 "자신의 답변에는 투표할 수 없습니다" 메시지가 나옵니다.
=> "로그인 후 투표해 주세요"라는 의미의 문구로 변경이 필요합니다.

<img width="1145" alt="image" src="https://github.com/Kernel360/f1-KernelSquare-backend/assets/1324021/f26f75b0-3748-4f4e-9a7d-5cb0f7a63946">

### Version

1.0.0 (Default)

### Code of Conduct

- [X] KernelSquare의 Code of Conduct에 동의합니다.

**Comment by Hju95** [comment]
조치하였습니다.
